[package]
name = "hello_rocket"
version = "0.1.0"
authors = ["wingleungchoi <wingleungchoi@gmail.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
